### ISSUE TITLE
Develop questionnaire completion tracking within series

### ISSUE THREAD

**Issue by stampaaaron** [openscript-ch/quassel#33]
- [x] No periods before birthdate
- [x]  Limit the questionnaires on the end of the current month
- [x] Save and continue to the next period
